# Generated by Django 5.1.2 on 2024-11-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='super_user_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
