# Generated by Django 5.1.2 on 2024-11-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogUser', '0002_alter_customuser_super_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users/%Y/%m/'),
        ),
    ]
