# Generated by Django 5.1.2 on 2024-11-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogUser', '0003_customuser_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='cover',
            new_name='profile_picture',
        ),
    ]
