# Generated by Django 5.1.2 on 2024-11-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogUser', '0004_rename_cover_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(upload_to='users/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='super_user_code',
            field=models.CharField(blank=True, help_text='Preencha este campo caso tenha uma chave para se tornar um superusuário', max_length=5),
        ),
    ]
