# Generated by Django 5.1.2 on 2024-11-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogUser', '0005_alter_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(help_text='Escolha uma foto quadrada para melhor resolução', upload_to='users/%Y/%m/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='super_user_code',
            field=models.CharField(blank=True, help_text='Preencha este campo caso tenha uma chave para se tornar um superusuário', max_length=5, verbose_name='Código de superusuário'),
        ),
    ]
