# Generated by Django 5.1.2 on 2024-11-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogUser', '0006_remove_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/user-no-img.jpg', help_text='Escolha uma foto quadrada para melhor resolução', null=True, upload_to='users/%Y/%m/', verbose_name='Foto de perfil'),
        ),
    ]
