# Generated by Django 5.1.2 on 2024-11-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='default/post-no-img.jpg', null=True, upload_to='posts/%Y/%m/'),
        ),
    ]
