# Generated by Django 5.1.2 on 2024-10-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted',
            new_name='published',
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default=None, upload_to='posts/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
