# Generated by Django 5.1.2 on 2024-10-31 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_alter_tag_slug_alter_tag_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
